// ============================================================
//  data-sunday.js  — Sunday League chapters
//  t1 Formations · t2 Pressing · t3 Set Pieces
//  s1 Striker Movement · m1 Midfielder Vision · d1 Defender Reading
// ============================================================
'use strict';

// ── t1 FORMATIONS ────────────────────────────────────────────
const _T1_CORE = [
  {difficulty:1,a:2,q:'In a 4-3-3 how many players are in each line?',opts:['5-3-2','3-4-3','4 defenders · 3 midfielders · 3 forwards','4-4-2 flat'],exp:'4-3-3: four defenders, three midfielders, three forwards — the most common modern formation.'},
  {difficulty:1,a:0,q:'What does "back four" mean?',opts:['Two centre-backs plus a left and right full-back','Four attacking players','The four best players','A 4-4-2 midfield'],exp:'The back four is two CBs flanked by two full-backs — the foundation of most modern defensive shapes.'},
  {difficulty:2,a:3,q:'Key difference between 4-4-2 and 4-3-3?',opts:['The goalkeeper','Number of defenders','Offside trap method','4-4-2 has two strikers and a flat four midfield; 4-3-3 has three midfielders and three forwards — attacking width comes differently'],exp:'4-4-2 uses two strikers for central presence; 4-3-3 creates width through wide forwards and uses the midfield three for control.'},
  {difficulty:2,a:1,q:'What is a "false 9" and why does it confuse defenders?',opts:['A keeper who attacks corners','A striker who drops deep pulling CBs out — follow them and space opens behind; ignore them and they receive freely in midfield','A midfielder disguised as a striker','A number 9 playing on the wing'],exp:'The false 9 creates an impossible CB dilemma: follow into midfield (leave a gap behind) or hold (let them receive freely).'},
  {difficulty:2,a:0,q:'What is a "diamond midfield" (4-1-2-1-2)?',opts:['Four midfielders in a diamond — holding base, two central, one attacking. Overloads centre but leaves width exposed, relying on full-backs','Only used in Spain','Same as a 4-4-2','A purely defensive system'],exp:'The diamond overloads central areas but requires attacking full-backs to provide width — a major tactical trade-off.'},
  {difficulty:3,a:2,q:'What is "positional play" most associated with?',opts:['Total Football 1970s','Direct counter-attack','Pep Guardiola — occupying the pitch to always have numerical and positional superiority, every pass moving the structure to create gaps','A 4-4-2 variant'],exp:'Positional play creates permanent superiority — the structure always leaves a 2v1 or open passing lane somewhere on the pitch.'},
  {difficulty:3,a:3,q:'What does a "high defensive line" require?',opts:['Defenders standing still','Only in 4-3-3','Formation choice only','Fast CBs who can recover, and a sweeping goalkeeper — compresses space and enables pressing but is vulnerable to balls in behind'],exp:'High lines need pace and a sweeping keeper — compressing space enables pressing but requires CBs who can recover quickly.'},
  {difficulty:4,a:1,q:'What is "gegenpressing" and who made it famous?',opts:['A Spanish possession system','Jürgen Klopp — immediately counter-pressing to win the ball back within seconds of losing it, catching the opponent disorganised in transition','A defensive 5-4-1','A 4-4-2 variant'],exp:'Gegenpressing exploits the transition moment — your team is already in forward positions (ideal pressing positions) the instant you lose the ball.'},
  {difficulty:4,a:0,q:'What is "asymmetric pressing"?',opts:['Using different press structures on each side — inviting the ball to one side where the press is strongest, funnelling opponents into a trap','Pressing only in the opponent half','Pressing with different intensities per player','Only used in European football'],exp:'Asymmetric pressing channels opponents into the trap — they feel they have freedom but are being guided into the zone where the press is strongest.'},
  {difficulty:4,a:2,q:'What is the difference between "formation" and "shape"?',opts:['They are the same','Formation is always static; shape always dynamic','Formation is the nominal starting structure (e.g. 4-3-3); shape is actual positioning during play — a 4-3-3 in possession often becomes a 3-2-5 with full-backs pushing on','Formation determines shape exactly'],exp:'Best analysts talk about shape not formation — a 4-3-3 can look like a 3-2-5 in possession and a 4-5-1 out of possession.'},
];

// ── t2 PRESSING & TRANSITIONS ────────────────────────────────
const _T2_CORE = [
  {difficulty:1,a:3,q:'What is a "transition" in football?',opts:['A substitute coming on','A formation change','A player changing position','The moment possession switches between teams — the most dangerous phase in modern football because both teams are temporarily disorganised'],exp:'Transitions are football\'s most dangerous moments — 3-5 seconds where both teams are out of shape and enormous opportunities exist.'},
  {difficulty:1,a:0,q:'What is a "pressing trigger"?',opts:['A pre-agreed signal that initiates the coordinated press simultaneously — a back pass, poor first touch, GK receiving — everyone presses the moment it occurs','Pressing whenever the striker feels like it','A signal from the manager only','A code word from the captain'],exp:'Pressing triggers coordinate the press — without them everyone presses at different moments and it is easily played through.'},
  {difficulty:2,a:1,q:'What is "counter-pressing"?',opts:['Pressing only on counters','Immediately pressing to win the ball back within 5 seconds of losing it — the team is already in attacking positions which are ideal pressing positions. Win it back immediately rather than resetting','Counter-attacking from deep','Only pressing when level'],exp:'Counter-pressing exploits the transition — both teams are temporarily disorganised after a turnover, and immediate pressing catches opponents before they organise.'},
  {difficulty:2,a:2,q:'What does PPDA measure?',opts:['Points Per Defensive Action','Player Performance Data','Passes Permitted per Defensive Action — lower PPDA means more aggressive pressing','Pressing Percentage During Attacks'],exp:'PPDA quantifies pressing intensity — it translates the abstract concept of pressing hard into a measurable number.'},
  {difficulty:3,a:0,q:'What is "organised pressing" vs "individual pressing"?',opts:['Organised: the entire team moves simultaneously to cover all passing options when one player initiates the press — making escape almost impossible. Individual: one or two players press randomly — easily beaten by a simple pass to the uncovered player','They are the same','Individual is always better','Organised is only for professional teams'],exp:'Organisation makes the press effective — individual pressing is easily beaten; organised pressing with full coverage creates turnovers consistently.'},
  {difficulty:2,a:3,q:'What are pressing intensity zones?',opts:['High, medium and low press are identical','Only the high press matters','Teams never press in their own half','High press (opponent third), mid-block (middle third), low block (own half). Each creates different risk-reward tradeoffs. Most teams vary depending on the situation, score and energy available'],exp:'Pressing zones are tactical choices — teams choose their pressing height based on opponent, score, and energy remaining.'},
  {difficulty:3,a:2,q:'What is "defensive transition" and why is it the hardest phase to organise?',opts:['Defending when winning','The switch from attack to defence when possession is lost — the whole team must immediately change mentality, direction and positioning. The hardest phase because players were in attacking positions and must instantly convert to defensive responsibilities','Only relevant for defenders','Only relevant in the final third'],exp:'Defensive transition is the most difficult organisational challenge — converting attacking momentum into defensive positioning in under a second requires automatic responses.'},
  {difficulty:4,a:1,q:'What is "offensive transition" at its best?',opts:['Attacking when winning','Immediately converting possession won in defence into a direct attack before the opposition can reorganise — the best teams score within 5-10 seconds of winning the ball because they read the transition before it happens. Speed of thought matters more than speed of feet','Counter-attack only from 20 yards','Only relevant for defensive teams'],exp:'Offensive transition excellence is pre-reading — the player already running as the tackle goes in, not waiting to see if the ball is won, creates the deadliest transitions.'},
  {difficulty:4,a:0,q:'What is "pressing to create fatigue"?',opts:['Using a high-intensity press not just to win the ball but to tire the opposition physically and mentally — forcing more passes under more pressure over 90 minutes. Teams pressed for 70 minutes make significantly more mistakes in the final 20','Only about winning the ball','Only about psychological pressure','Only effective in the first 30 minutes'],exp:'Fatigue creation is the delayed reward of pressing — the press that does not win the ball immediately is still creating the fatigue that produces turnovers in the 75th minute.'},
  {difficulty:4,a:2,q:'What is the "press trap"?',opts:['Trapping the ball near the corner flag','Only relevant in the opponent box','Deliberately allowing the opposition to pass into a specific zone (inviting them with the press shape) and then springing a coordinated press once the ball arrives — the opposition thinks they have escaped; they have walked into the trap','Only relevant for professional teams'],exp:'The press trap is sophisticated deception — the team appears to concede space but uses the press shape to invite the ball into the zone where they can win it most effectively.'},
];

// ── t3 SET PIECES ─────────────────────────────────────────────
const _T3_CORE = [
  {difficulty:1,a:2,q:'What percentage of professional football goals come from set pieces?',opts:['Around 5%','Around 15%','Around 25-30% — set pieces are one of the most efficient ways to score, which is why clubs now employ dedicated set piece coaches','Around 50%'],exp:'Set pieces are the most "trainable" source of goals — practice directly improves effectiveness more than any other area of football.'},
  {difficulty:1,a:0,q:'What is a "near post run" at a corner?',opts:['A run to the post closest to the corner flag to create a flick-on or deflection that changes the ball\'s direction in a way the goalkeeper cannot predict','Running away from the corner','Standing at the back post','A run to the penalty spot'],exp:'Near post runs create deflections and flick-ons — the redirected ball goes somewhere completely unpredictable, which is precisely what makes them dangerous.'},
  {difficulty:2,a:3,q:'What is the difference between zonal and man-to-man corner defending?',opts:['They are the same','Zonal is only for big clubs','Man-to-man is always better','Zonal: players cover areas challenging whoever enters their zone. Man-to-man: each defender follows a specific attacker regardless of where they move. Both are effective — zonal prevents organised runs; man-to-man creates clear responsibility but can be exploited by pick moves'],exp:'The zonal vs man-marking debate is genuinely unresolved — both approaches have clear advantages and disadvantages which is why professional clubs still disagree.'},
  {difficulty:2,a:1,q:'What is an "inswinging" corner and why is it dangerous?',opts:['A corner that curves away from goal','A corner that curves into the goalmouth — toward the goal. Dangerous because it can go in directly if not claimed, creates awkward contact for defenders heading away, and forces the goalkeeper to either commit or hold','A corner hit too softly','A corner from the left side only'],exp:'Inswinging corners are dangerous for multiple reasons — they can score directly AND create the most awkward deflections for defenders trying to head clear.'},
  {difficulty:2,a:0,q:'How many players are in a typical free kick wall and what does it cover?',opts:['Typically 3-5 players covering the direct route to goal — the wall covers the near-post area while the goalkeeper covers the far post. Exact number depends on distance and angle','10 players always','Only 2 players','The goalkeeper stands in the wall'],exp:'Wall size depends on the threat — closer, more central free kicks require bigger walls because the direct route covers more of the goal.'},
  {difficulty:3,a:2,q:'What is a "short corner" and what tactical advantage does it create?',opts:['A corner passed back to the goalkeeper','A corner hit hard to the near post','Playing a short pass to a teammate near the corner flag — drawing defenders out of their positions, creating a better crossing angle, or creating a 2v1 on the near touchline','A corner that is cleared quickly'],exp:'Short corners are position disruptors — they force defenders to choose between tracking runners and covering the short pass, breaking the organised defensive structure before the actual cross.'},
  {difficulty:3,a:3,q:'What is a "dummy run" at a set piece and why is it as valuable as the scoring run?',opts:['A run made by a substitute','A practice run in training','A run toward a specific defender just to block them','A run made specifically to take a defender out of position — allowing another attacker to receive in the freed space. The player making the dummy run does not expect to receive but their movement creates the space someone else exploits'],exp:'Dummy runs are as valuable as scoring runs — the well-designed set piece routine includes players whose explicit job is to take defenders away from the actual scorer\'s receiving zone.'},
  {difficulty:4,a:1,q:'What is a "set piece coach" and why have elite clubs added one?',opts:['A dedicated analyst only','A specialist who analyses opponent set piece vulnerabilities, designs attacking routines, leads specific training and prepares defensive set piece structure. With 25-30% of goals coming from set pieces, having a specialist creates a direct competitive advantage','Only relevant at international level','The same as a tactical analyst'],exp:'Set piece specialisation reflects the goal percentage — if 30% of goals come from set pieces, employing a dedicated coach for that 30% is as logical as employing any other specialist coach.'},
  {difficulty:4,a:2,q:'What is VAR\'s impact on set pieces in modern football?',opts:['No impact','Only affects offside decisions','VAR reviews have significantly changed set piece design — teams now must account for handball checks, millimetre-precise offside decisions and referee reviews. Routines are designed to avoid positions that create VAR controversy, and defensive positioning has adjusted to avoid accidental handball risk','Only affects penalty decisions'],exp:'VAR has changed set piece design — teams specifically design corners and free kicks to avoid positions that trigger VAR reviews.'},
  {difficulty:4,a:0,q:'What is the most analytically sophisticated approach to set piece design?',opts:['Using opponent goalkeeper analysis — identifying whether they prefer to claim or punch, their command radius, their handling under physical contact, their reaction to decoys. Then designing delivery specifically to exploit those weaknesses','Only standard corner routines','Only direct free kicks','Only short corners'],exp:'Goalkeeper-specific set piece design is the highest analytical sophistication — every detail of the routine designed around the specific goalkeeper\'s identified weaknesses rather than standard templates.'},
];

// ── s1 STRIKER MOVEMENT & FINISHING ──────────────────────────
const _S1_CORE = [
  {difficulty:1,a:2,q:'What is a "blindside run" for a striker?',opts:['Running when the referee is not watching','Running backwards to receive','Making a run into the space the defender cannot see without turning — getting between the defender\'s vision and their body so they must either turn (losing position) or guess','Running at the goalkeeper'],exp:'Blindside runs exploit defender vision — a defender can only see what is in front of them; getting behind their eyeline forces them to either turn or guess.'},
  {difficulty:1,a:0,q:'What is "hold-up play" and why is it essential for a striker?',opts:['Receiving the ball with back to goal, shielding it from the defender, and creating time for teammates to advance — making the striker the team\'s pivot point in attack','Deliberately slowing the game down','Only running in behind the defence','Staying near the opposition goalkeeper'],exp:'Hold-up play converts the striker into the team\'s link player — one player receiving and holding creates movement from six others, multiplying attacking options from a single action.'},
  {difficulty:1,a:3,q:'What is a "poacher\'s goal"?',opts:['A long-range thunderbolt','A header from a cross','A goal scored through skill','A goal from a rebound, deflection or loose ball inside the six-yard box — requiring the striker to always be in the right place. Poachers score inevitable ones because they are always where the ball ends up'],exp:'Poaching is position and instinct — the poacher\'s gift is anticipating where the ball will be in the box before it arrives.'},
  {difficulty:2,a:1,q:'What is "timing the run" to stay onside?',opts:['Starting every run early','Watching the last defender\'s line and beginning the run at the exact moment the ball is played — the striker\'s front foot must be behind the second-to-last defender when the ball leaves the passer\'s foot. Too early = offside; too late = chance has gone','Always starting runs when the ball is passed','Only relevant for fast strikers'],exp:'Onside timing is the striker\'s most important cognitive skill — a split-second difference between perfect timing and offside determines whether the chance exists at all.'},
  {difficulty:2,a:0,q:'What is a "striker\'s dummy" — faking to receive, then letting the ball run?',opts:['Pretending to control the ball but letting it run to a teammate behind you — using your body to deceive the defender who was tracking the ball. Works when you have already scanned and know a teammate is in a better position behind you','A training technique only','A foul technique','Only used in tight spaces'],exp:'The dummy is intelligence disguised as inaction — letting the ball run exploits the defender\'s focus on the ball to create an opportunity for the player receiving behind you.'},
  {difficulty:3,a:3,q:'What is "the third man run" for a striker?',opts:['A run made by the third-choice striker','A run in the third phase of an attack','Only relevant in a 4-3-3','Player A passes to B; B passes back to A; C (the striker) makes the run into the space the defensive attention to A and B created. The striker arrives unmarked because the defence was preoccupied with tracking the two passing players'],exp:'Third man runs are football\'s most elegant attacking pattern — two players attract defensive attention; the third player arrives in the gap their movement created.'},
  {difficulty:3,a:2,q:'What is "composure in front of goal"?',opts:['Never feeling nervous','Always rushing the shot','Not panicking in the moment of opportunity — processing the goalkeeper\'s position, the available target zones, and the optimal technique in under a second, then executing without hesitation. Great strikers slow down mentally at the most intense moments rather than speeding up','Only relevant for experienced strikers'],exp:'Composure is controlled cognitive processing under adrenaline — the brain wants to rush, but elite finishers override this with a moment of clarity that produces cleaner technique and better decision-making.'},
  {difficulty:4,a:1,q:'What is "working on the shoulder" of a defender?',opts:['Physical contact with the defender','Staying at a position on the defender\'s last man line — right on their shoulder — making it impossible for them to both see you and see the ball simultaneously. From this position the striker can dart either side the moment the ball is played','Running directly at the defender','Only relevant against tall defenders'],exp:'Shoulder positioning is a permanent threat — staying in the defender\'s visual blind spot forces them to constantly look between ball and striker.'},
  {difficulty:4,a:0,q:'What is the "striker as creator" in modern football?',opts:['A striker who contributes to build-up play, creates chances for teammates through movement, draws defenders out of position to create space for others, and links play between midfield and attack — modern pressing systems require strikers who contribute in the 75 minutes when they are not near the opposition goal','The same as a false 9 only','Not relevant for goal-scorers','Only relevant for target strikers'],exp:'The modern striker\'s contribution spans the whole pitch — the window near the goal has expanded into a 90-minute role including press leading, link play and movement that creates for others.'},
  {difficulty:4,a:2,q:'What separates an elite finisher from a very good one?',opts:['Elite finishers score more goals','Elite finishers are faster','Consistency of execution under any type of pressure — not just composure in clear-cut chances, but maintaining technical quality in difficult finishes (tight angles, under challenge, one-touch, volleys) without degradation. Very good finishers execute well from clear positions; elite finishers maintain the same quality from difficult positions','Elite finishers only score easy goals'],exp:'Technical consistency across all chance types is the elite standard — the difference between very good and elite is not the quality from easy chances but maintaining that quality from difficult ones.'},
];

// ── m1 MIDFIELDER VISION & PRESS RESISTANCE ──────────────────
const _M1_CORE = [
  {difficulty:1,a:1,q:'What does "scanning" mean in midfield?',opts:['Looking at the ball only','Regularly checking surroundings before receiving so you already know your next action','Using technology','Checking the scoreboard'],exp:'Elite midfielders scan constantly — the decision is made before the ball arrives.'},
  {difficulty:1,a:3,q:'What is "press resistance"?',opts:['Physical training','Pressing opponents yourself','Avoiding training','Staying composed under pressure and finding the right pass or escape route when an opponent closes you down'],exp:'Press resistance is composure under fire — the ability to receive and maintain possession when pressed.'},
  {difficulty:2,a:0,q:'What is "playing with your head up"?',opts:['Scanning the pitch continuously before and after receiving the ball — gathering information about teammates, opponents and space so your decisions are based on a full picture of the game rather than just what is directly in front of you','Looking upward when jumping','A coaching metaphor only','Only relevant for tall players'],exp:'Heads-up play is information gathering — the more information you have before the ball arrives, the better the decision you can make.'},
  {difficulty:2,a:2,q:'What is the "triangle" in possession football?',opts:['Three passes in a row','A 4-3-3 formation','Creating three passing options at all times — one on each side and one behind — so no matter which direction the opposition closes, there is always a free receiver. It makes pressing almost mathematically impossible','A training drill'],exp:'Triangles defeat pressing — three options always leave at least two free no matter where the pressure comes from.'},
  {difficulty:3,a:1,q:'What is "receiving on the half-turn"?',opts:['Turning 90 degrees before receiving','Positioning so that when you receive the ball your body is angled to see both the ball AND the pitch simultaneously — immediately able to pass either direction without an additional turn','A shooting technique','Only relevant for attackers'],exp:'Half-turn receiving is instant possession — you see options before the ball arrives and can act immediately rather than turning first.'},
  {difficulty:3,a:3,q:'What is the "pivot" in modern football?',opts:['A full-back technique','A winger movement','An attacking midfielder role','A defensive midfielder who receives under pressure, shields the ball and distributes — connecting defence to attack while screening the back four. The most demanding positional role in football'],exp:'The pivot is the team\'s connector — they receive under pressure and distribute intelligently, making them the most important passer in the team.'},
  {difficulty:4,a:0,q:'What is "tempo manipulation" for a central midfielder?',opts:['Deliberately varying passing speed to control the game — slow tempo to draw opponents forward, sudden quickening to exploit the space they vacated. A great midfielder controls the game\'s pace, deciding when to accelerate and when to slow down to manipulate the opponent\'s shape','Always passing fast','Always passing slow','Only relevant for holding midfielders'],exp:'A great midfielder controls the game\'s pace — they decide when to accelerate and when to slow down, manipulating the opponent\'s shape.'},
  {difficulty:4,a:3,q:'What is "passing in pockets" for a central midfielder?',opts:['Passing in small areas only','Short passes only','Only relevant for the number 10','Receiving between the opposition\'s defensive and midfield lines — the most dangerous zone in possession football. From this position you can immediately face forward and threaten the defensive line. Getting into this position is the central midfielder\'s highest offensive achievement'],exp:'The pocket between lines is the most dangerous position to receive in — one touch and you are facing goal with the defensive line behind you.'},
  {difficulty:4,a:1,q:'What separates elite midfielders like De Bruyne and Modric from average ones?',opts:['They pass faster','Every touch is directional — it lands exactly where the next pass can be delivered instantly, as if the control and the pass are a single flowing movement. Their scan before receiving already contains the next two passes in mind','They pass backward more','They always look to shoot'],exp:'Elite midfield touch is not just control — it is instant preparation. The ball arrives and the next pass is already lined up.'},
  {difficulty:4,a:2,q:'What is the highest contribution a midfielder makes that never appears in statistics?',opts:['Winning the ball back','Making assists','The "ghost run" — moving into a specific position that draws a defender away from the zone a teammate will exploit. The space-creating run that enables a striker\'s goal is the midfielder\'s most valuable and least recognised contribution. It requires reading the game 2-3 passes ahead and being willing to work for the team\'s benefit with no personal statistical reward','Only relevant for the most expensive players'],exp:'Ghost runs create unmeasured value — the midfielder who consistently creates space for others contributes to goals that statistics will never record but that matter as much as any other attacking action.'},
];

// ── d1 DEFENDER READING THE GAME ─────────────────────────────
const _D1_CORE = [
  {difficulty:1,a:3,q:'What is "anticipation" for a defender?',opts:['Feeling nervous','Guessing randomly','Fouling attackers early','Reading the play before it happens and positioning accordingly — great defenders are already in position because they read two passes ahead'],exp:'Great defenders are already in position — they read two passes ahead of where the ball currently is.'},
  {difficulty:1,a:0,q:'Why should centre-backs communicate constantly?',opts:['To organise the defensive line, alert teammates to runners and call for the ball','They are the loudest players','Only to speak to the goalkeeper','To shout at the opposition'],exp:'The CB is the team\'s organiser — their voice controls the line.'},
  {difficulty:2,a:2,q:'What is "defensive organisation"?',opts:['The formation the team uses','Only set piece positioning','A structured collective defensive system where each defender knows their role and responsibilities — creating a shape that is greater than the sum of individual defensive abilities. Organisation converts individual quality into team defensive excellence','Only relevant for professional teams'],exp:'Organisation multiplies individual quality — organised defenders consistently beat more talented but disorganised defenders across a full season.'},
  {difficulty:2,a:1,q:'What is "jockeying" for a centre-back?',opts:['Always tackling immediately','Staying in front of the attacker, moving backward while they move forward, staying low and balanced — channelling them toward a less dangerous area while waiting for the right moment to tackle or forcing them away from goal','Jumping to head the ball','Running at the attacker'],exp:'Jockeying is patience made physical — staying in front of the attacker, taking away their options, waiting for the mistake.'},
  {difficulty:2,a:3,q:'What is "stepping out to press" and when is it appropriate?',opts:['Never — CBs should never step out','Always step out when the striker receives','Only step out when the goalkeeper tells you','When the striker receives with their back to goal — stepping out aggressively from behind to press immediately can win the ball before the striker can turn. Only appropriate when the other CB is in position to cover the space created by the step-out'],exp:'Stepping out to press from behind the striker is the CB\'s most effective ball-winning action when the striker is facing away from goal.'},
  {difficulty:3,a:0,q:'What is "recovering goalside" when beaten by a forward?',opts:['Sprinting at an angle to get between the attacker and the goal — not chasing the ball but positioning to cut the route to goal. The diagonal recovery rather than the straight chase is what creates the opportunity to save the situation by forcing the attacker wide where cover exists','Sprinting directly toward the attacker','Waiting for the attacker to shoot','Shouting for the goalkeeper'],exp:'Diagonal recovery creates goalside position — running to the right position (goalside, angled) is more effective than running in a straight line toward the attacker when you are already beaten.'},
  {difficulty:3,a:2,q:'What is "the defensive line\'s collective intelligence"?',opts:['The fastest CB in the defensive line','The CB with the most experience','The collective decision-making — stepping up for offside simultaneously, dropping together when a ball is played behind, communicating about runners and adjusting the line height based on the pressing shape. When the collective works in harmony the defensive line is almost unbeatable; when one player is late or miscommunicates the entire defensive structure fails','Only relevant at professional level'],exp:'Collective line intelligence is the sum of individual decisions made at the same moment — the weakest link determines the whole line\'s effectiveness.'},
  {difficulty:4,a:3,q:'What is the "art of delaying" for a centre-back?',opts:['Only time-wasting','Running away from the attacker','Heading the ball away as fast as possible','Slowing the attacker down to allow teammates to recover — not tackling immediately when beaten but using positioning and movement to reduce their speed and options, buying 2-3 seconds that allow the midfield to recover and cover the space behind. The delay that enables collective defence is more valuable than the reckless tackle that creates a clear chance'],exp:'Delaying is courage — accepting momentary individual defeat to create the conditions for collective defensive success is one of the hardest psychological demands in defending.'},
  {difficulty:4,a:1,q:'What is the highest CB quality that coaches struggle to teach?',opts:['Tackling technique','Anticipation — knowing where the ball will be in two passes. Impossible to coach directly; it emerges from thousands of hours watching the game, understanding attacking patterns and developing the spatial awareness to read play before it unfolds. A CB with elite anticipation is rarely in the wrong position; one without it is always reacting','Heading technique','Positional discipline'],exp:'Anticipation is the rarest defensive quality — it emerges from experience and deep game understanding, not from coaching sessions.'},
  {difficulty:4,a:2,q:'What is the highest standard for a CB pairing\'s collective understanding?',opts:['Winning every individual duel','Communicating frequently','When both CBs understand each other\'s tendencies so completely that they automatically cover each other\'s movements without verbal communication — one steps out, the other drops automatically; one goes to head, the other positions for the second ball. This telepathic understanding is built through thousands of hours playing together and studying the game as a pair','Matching each other in pace'],exp:'Telepathic CB pairing is football\'s most underrated quality — when two CBs develop automatic mutual coverage, the defensive structure becomes almost impenetrable because there are never gaps between them.'},
];

// ══════════════════════════════════════════════════════════════
//  Helper — build a position-variant chapter from core + position pools
//  For sunday chapters we use the core pool for all positions
//  (enough to fill all levels with 10 questions each)
// ══════════════════════════════════════════════════════════════
function _buildChapter(id, title, emoji, cat, order, core) {
  return {
    id, title, emoji, cat, order,
    questions: {
      core,
      // All positions share the same pool — core is rich enough
      Striker: core,
      Midfielder: core,
      Winger: core,
      'Full-Back': core,
      Defender: core,
      Goalkeeper: core,
      'All-Rounder': core,
    }
  };
}

const SUNDAY_CHAPTERS = [
  _buildChapter('t1','Formations Explained','📋','Tactics',11,_T1_CORE),
  _buildChapter('t2','Pressing & Transitions','⚡','Tactics',12,_T2_CORE),
  _buildChapter('t3','Set Pieces','🎯','Tactics',13,_T3_CORE),
  _buildChapter('s1','Striker: Movement & Finishing','⚡','Position',14,_S1_CORE),
  _buildChapter('m1','Midfielder: Vision & Press Resistance','🎯','Position',15,_M1_CORE),
  _buildChapter('d1','Defender: Reading the Game','🛡️','Position',16,_D1_CORE),
];

// ── Merge into ALL_CHAPTERS ───────────────────────────────────
(function() {
  if (typeof ALL_CHAPTERS === 'undefined') {
    console.warn('data-sunday.js: ALL_CHAPTERS not found — skipping merge');
    return;
  }
  const existingIds = new Set(ALL_CHAPTERS.map(c => c.id));
  let added = 0;
  SUNDAY_CHAPTERS.forEach(ch => {
    if (!existingIds.has(ch.id)) {
      ALL_CHAPTERS.push(ch);
      added++;
    }
  });
  ALL_CHAPTERS.sort((a, b) => (a.order || 99) - (b.order || 99));
  console.log('Footy Brain: data-sunday.js loaded — ' + added + ' chapters added, ' + ALL_CHAPTERS.length + ' total chapters');
})();
