// ============================================================
//  Footy Brain — drills.js
//  Drill of the Day — 60 drills covering all positions,
//  seeded by date so the drill changes every day.
//  Each drill has a description, diagram steps, difficulty
//  and position tags.
// ============================================================

'use strict';

const ALL_DRILLS = [

  // ── BALL CONTROL ────────────────────────────
  {
    id: 'bc1',
    title: 'Toe Taps',
    emoji: '⚽',
    category: 'Ball Control',
    difficulty: 1,
    duration: '5 mins',
    positions: ['All'],
    equipment: ['1 ball'],
    tagline: 'The most important warm-up drill in football.',
    description: 'Stand over the ball and alternate tapping the top of it with your left and right foot as fast as you can. Keep your knees slightly bent and stay on your toes throughout.',
    steps: [
      'Place the ball on the ground in front of you',
      'Lightly tap the top of the ball with your right foot, then left foot',
      'Start slow — get the rhythm right first',
      'Build speed gradually — aim for 60 taps in 30 seconds',
      'Keep your head up as much as possible',
    ],
    coaching_tip: 'Don\'t stamp on the ball — light touches only. Imagine the ball is an egg.',
    xp: 10,
  },

  {
    id: 'bc2',
    title: 'Inside-Outside Dribble',
    emoji: '🔄',
    category: 'Ball Control',
    difficulty: 1,
    duration: '8 mins',
    positions: ['All'],
    equipment: ['1 ball', '4 cones'],
    tagline: 'Master close control with both sides of your foot.',
    description: 'Set up 4 cones in a straight line, 1 metre apart. Dribble through them using only the inside and outside of one foot — no laces. Then repeat with the other foot.',
    steps: [
      'Place 4 cones in a line, 1 metre apart',
      'Start at one end with the ball at your feet',
      'Use inside of foot to push ball right of first cone',
      'Use outside of foot to pull it back left of second cone',
      'Continue through all cones, then turn and come back',
      'Do 3 sets with right foot, 3 sets with left foot',
    ],
    coaching_tip: 'Keep the ball within one stride of your foot at all times — if it gets away from you, slow down.',
    xp: 15,
  },

  {
    id: 'bc3',
    title: 'Wall Passing',
    emoji: '🧱',
    category: 'Ball Control',
    difficulty: 1,
    duration: '10 mins',
    positions: ['All'],
    equipment: ['1 ball', 'a wall'],
    tagline: 'The best solo passing drill there is.',
    description: 'Stand 3 metres from a wall. Pass the ball against the wall using the inside of your foot and control the return with a cushioned first touch. Vary the distance and pace.',
    steps: [
      'Stand 3 metres from the wall',
      'Pass firmly with the inside of your right foot',
      'As it returns, cushion it with the inside of your left foot',
      'Pass back immediately — try to keep it going without stopping',
      'After 2 mins, increase distance to 5 metres',
      'After another 2 mins, try one-touch passing',
    ],
    coaching_tip: 'Focus on your first touch — it should stop the ball dead, not bounce away.',
    xp: 15,
  },

  {
    id: 'bc4',
    title: 'Juggling Challenge',
    emoji: '🎪',
    category: 'Ball Control',
    difficulty: 2,
    duration: '10 mins',
    positions: ['All'],
    equipment: ['1 ball'],
    tagline: 'Builds feel for the ball like nothing else.',
    description: 'Keep the ball off the ground using your feet, thighs and head. Start with a target of 10 consecutive touches and build from there. Record your best score.',
    steps: [
      'Drop the ball from your hands and let it bounce once, then kick it up',
      'Try to keep it in the air — use feet, knees or thighs',
      'Count each touch — that\'s your score',
      'If it hits the ground, start again',
      'Target: 10 → 20 → 50 → 100',
      'Try alternating feet only for extra challenge',
    ],
    coaching_tip: 'Hit the bottom half of the ball to send it straight up — hitting the middle sends it sideways.',
    xp: 20,
  },

  {
    id: 'bc5',
    title: 'First Touch Under Pressure',
    emoji: '🎯',
    category: 'Ball Control',
    difficulty: 3,
    duration: '10 mins',
    positions: ['All'],
    equipment: ['1 ball', '2 cones', 'a partner or wall'],
    tagline: 'Simulate match pressure on every touch.',
    description: 'Set up two cones 2 metres apart as a target. Partner throws or passes the ball from 8 metres away. You must control it in one touch so it ends up between the cones.',
    steps: [
      'Set up 2 cones 2 metres apart, 2 metres in front of you',
      'Partner stands 8 metres away with the ball',
      'They throw or pass — you control with ONE touch into the cone target',
      'Vary: bouncing ball, aerial ball, fast pass, slow pass',
      'Count how many out of 10 land between the cones',
      'Switch roles after 10 attempts',
    ],
    coaching_tip: 'Your first touch IS your second touch — use it to set yourself up for the next action.',
    xp: 25,
  },

  // ── PASSING ──────────────────────────────────
  {
    id: 'pa1',
    title: 'Triangle Passing',
    emoji: '🔺',
    category: 'Passing',
    difficulty: 1,
    duration: '10 mins',
    positions: ['All'],
    equipment: ['1 ball', '3 cones', '3 players ideally'],
    tagline: 'The foundation of all team passing play.',
    description: 'Set up 3 cones in a triangle, 5 metres apart. Three players stand at each cone. Pass to the right, follow your pass and rotate. Then pass to the left. Keep it crisp and one-touch.',
    steps: [
      'Set up a triangle with cones 5 metres apart',
      'One player at each cone',
      'Player A passes to Player B, then follows the pass to take B\'s position',
      'B passes to C and follows, C passes to A and follows',
      'Keep rotating — 2 minutes clockwise, 2 minutes anticlockwise',
      'Progress to one-touch only',
    ],
    coaching_tip: 'Pass and MOVE immediately — standing still after a pass kills the drill.',
    xp: 15,
  },

  {
    id: 'pa2',
    title: 'Long Passing Accuracy',
    emoji: '📏',
    category: 'Passing',
    difficulty: 2,
    duration: '10 mins',
    positions: ['Midfielder', 'Defender', 'All-Rounder'],
    equipment: ['1 ball', '4 cones'],
    tagline: 'Develop the range to switch play effectively.',
    description: 'Set up two target zones (2 cones each) 20 metres apart and 3 metres wide. Strike long passes from one zone to land in the other. Score 1 point per accurate pass. Target: 7/10.',
    steps: [
      'Mark two target zones with 2 cones each, 20 metres apart',
      'Stand behind one zone with the ball',
      'Strike a driven pass aimed at the opposite target zone',
      'Score 1 point if the ball lands within the cones',
      'Aim for 7 out of 10 accurate passes',
      'Vary: left foot, right foot, driven, lofted',
    ],
    coaching_tip: 'Plant foot points at the target — if you miss left or right, check your plant foot direction.',
    xp: 20,
  },

  {
    id: 'pa3',
    title: 'One-Two Combination',
    emoji: '↔️',
    category: 'Passing',
    difficulty: 2,
    duration: '8 mins',
    positions: ['All'],
    equipment: ['1 ball', '2 cones', '2 players'],
    tagline: 'The most effective pass in football — give and go.',
    description: 'Player A passes to Player B (the wall) and immediately runs beyond a cone 5 metres ahead. B plays the return first-time into the space. A receives on the run.',
    steps: [
      'Place a cone 5 metres ahead of Player A',
      'A passes to B who stands 4 metres away at an angle',
      'As soon as A passes, they sprint beyond the cone',
      'B plays the ball first-time into the space beyond the cone',
      'A receives on the run, controls, and they reset',
      'Swap roles every 5 repetitions',
    ],
    coaching_tip: 'Don\'t wait to see if the pass is good before running — pass and go simultaneously.',
    xp: 20,
  },

  {
    id: 'pa4',
    title: 'Rondo (5v2)',
    emoji: '🔵',
    category: 'Passing',
    difficulty: 3,
    duration: '15 mins',
    positions: ['All'],
    equipment: ['1 ball', 'bibs', '7 players'],
    tagline: 'The drill used by every top team in the world.',
    description: 'Five players form a circle roughly 8 metres wide. Two players in the middle try to win the ball. Outer players keep possession using one or two touches. If the middle wins it, the player who lost it goes in.',
    steps: [
      'Form a circle with 5 players — roughly 8 metres diameter',
      'Two players start in the middle',
      'Outer players pass to each other, avoiding the two inside',
      'Maximum 2 touches (1 touch for advanced players)',
      'If a middle player wins the ball or it goes out — the player responsible goes in the middle',
      'Play for 10 minutes straight — keeps everyone sharp',
    ],
    coaching_tip: 'The spare player (not being pressed) must constantly offer an angle — never stand still behind the action.',
    xp: 25,
  },

  // ── SHOOTING ─────────────────────────────────
  {
    id: 'sh1',
    title: 'Shooting on the Turn',
    emoji: '🔄',
    category: 'Shooting',
    difficulty: 2,
    duration: '10 mins',
    positions: ['Striker', 'Midfielder', 'All-Rounder'],
    equipment: ['6 balls', '2 cones', 'a goal'],
    tagline: 'Score before defenders can react.',
    description: 'Stand with your back to goal 12 metres out. Partner plays a ball to your feet. Receive, turn in one movement and shoot. No extra touches. Target: 6 goals from 10 shots.',
    steps: [
      'Stand 12 metres from goal, back to goal',
      'Partner stands 8 metres behind you with the ball',
      'They pass to your feet',
      'Open your body as the ball arrives and take it on the half-turn',
      'Shoot first or second touch — no more',
      'Vary: turn left and shoot, turn right and shoot, fake the turn',
    ],
    coaching_tip: 'The turn and the shot should feel like one movement — receive, turn, shoot is three steps but feels like one.',
    xp: 20,
  },

  {
    id: 'sh2',
    title: 'Finishing from Crosses',
    emoji: '🏹',
    category: 'Shooting',
    difficulty: 2,
    duration: '12 mins',
    positions: ['Striker', 'All-Rounder'],
    equipment: ['6 balls', 'a goal', '2 players'],
    tagline: 'Score from the most common chance in football.',
    description: 'Crosser stands on the wing with 6 balls. Striker starts at the penalty spot and makes a run to meet the cross. Crosser delivers — striker finishes. Alternate low crosses, driven crosses, floated crosses.',
    steps: [
      'Crosser stands wide right or wide left with 6 balls',
      'Striker starts at the penalty spot',
      'Striker makes a run — near post, far post, or penalty spot',
      'Crosser delivers when the striker starts their run',
      'Striker finishes first time if possible',
      '6 crosses from each side — count goals',
    ],
    coaching_tip: 'Attack the ball — don\'t wait for it to come to you. Arrive at the ball, don\'t let the ball arrive at you.',
    xp: 20,
  },

  {
    id: 'sh3',
    title: 'Penalty Pressure',
    emoji: '🥅',
    category: 'Shooting',
    difficulty: 2,
    duration: '10 mins',
    positions: ['All'],
    equipment: ['5 balls', 'a goal', 'a goalkeeper'],
    tagline: 'Practise the most pressured moment in football.',
    description: 'Take 5 penalties. Before each one, do 10 burpees first to simulate fatigue and pressure. Pick your spot before you start your run-up. Don\'t change your mind.',
    steps: [
      'Place the ball on the penalty spot',
      'Do 10 burpees (or 20 star jumps) immediately before each kick',
      'DECIDE which corner before you start your run-up',
      'Commit to the decision — do not change it mid-run',
      'Strike with the inside of the foot for placement or laces for power',
      'Take 5 penalties — count how many you score',
    ],
    coaching_tip: 'Decide your spot, look at it once, then look at the ball. Trust your decision. Changing your mind mid-run is the biggest cause of missed penalties.',
    xp: 20,
  },

  {
    id: 'sh4',
    title: 'Volley Technique',
    emoji: '💥',
    category: 'Shooting',
    difficulty: 3,
    duration: '10 mins',
    positions: ['Striker', 'Midfielder', 'All-Rounder'],
    equipment: ['6 balls', 'a goal', 'a server'],
    tagline: 'One of football\'s hardest and most spectacular techniques.',
    description: 'Server tosses the ball underarm from 6 metres. Strike it on the volley before it bounces, aiming low at the corners. Focus on technique — keep your toe down and ankle locked.',
    steps: [
      'Server stands 6 metres away to the side',
      'They toss the ball underarm at medium height',
      'Strike the ball before it bounces — keep your ankle locked',
      'Toe pointing down, lean slightly over the ball',
      'Aim for low corners — high volleys are easy to save',
      '10 attempts each side, count goals',
    ],
    coaching_tip: 'Toe down, ankle locked, head over the ball — the three keys to a clean volley. Power comes from technique, not swinging hard.',
    xp: 25,
  },

  // ── DEFENDING ────────────────────────────────
  {
    id: 'de1',
    title: 'Jockeying Drill',
    emoji: '🛡️',
    category: 'Defending',
    difficulty: 1,
    duration: '8 mins',
    positions: ['Defender', 'Midfielder', 'All-Rounder'],
    equipment: ['1 ball', '4 cones', '2 players'],
    tagline: 'The most important defensive skill — patience.',
    description: 'Mark a 10x5 metre channel with cones. Attacker tries to dribble from one end to the other. Defender must jockey — staying low, side-on, balanced — without diving in. After 30 seconds, swap.',
    steps: [
      'Mark a 10x5 metre channel',
      'Attacker starts at one end, defender faces them',
      'Attacker dribbles toward the defender',
      'Defender jockeys — side-on, low, on toes, channelling toward the side',
      'NO TACKLING for the first minute — just jockey',
      'After 1 minute, defender can tackle when they\'re certain',
    ],
    coaching_tip: 'Stay 1-2 metres away — too close and they beat you with a feint, too far and they run past you. Control the distance.',
    xp: 15,
  },

  {
    id: 'de2',
    title: 'Recovery Run',
    emoji: '🏃',
    category: 'Defending',
    difficulty: 2,
    duration: '8 mins',
    positions: ['Defender', 'Midfielder', 'All-Rounder'],
    equipment: ['1 ball', '4 cones', '2 players'],
    tagline: 'Getting beaten is fine — not recovering is not.',
    description: 'Defender starts 3 metres behind the attacker. Attacker has a head start toward goal. Defender must sprint to catch up and get goalside before the attacker shoots.',
    steps: [
      'Set up a goal (or two cones) at one end',
      'Attacker stands 15 metres from goal',
      'Defender starts 3 metres BEHIND the attacker',
      'On the signal, attacker runs toward goal, defender sprints to recover',
      'Defender\'s goal: get goalside before the shot',
      'Attacker\'s goal: shoot before the defender recovers',
    ],
    coaching_tip: 'Sprint on the inside of the attacker\'s path — the shortest route to goalside. Don\'t chase their shoulder.',
    xp: 20,
  },

  {
    id: 'de3',
    title: 'Heading Duel',
    emoji: '🏹',
    category: 'Defending',
    difficulty: 2,
    duration: '10 mins',
    positions: ['Defender', 'All-Rounder'],
    equipment: ['1 ball', '2 players'],
    tagline: 'Win the air and you control the game.',
    description: 'Two players stand facing each other. Server tosses the ball between them. Both players compete to win the header. Focus on timing your jump and attacking the ball.',
    steps: [
      'Two players stand 1 metre apart facing each other',
      'Server stands 3 metres away',
      'Server tosses the ball between the two players',
      'Both jump to head it — timing and jump are everything',
      'Winner scores a point — first to 5 wins',
      'Progress: server varies height, distance and timing',
    ],
    coaching_tip: 'Jump OFF one foot for more height and control — two-footed jumps are slower. Attack the ball, don\'t wait for it.',
    xp: 20,
  },

  {
    id: 'de4',
    title: 'Tackle Timing',
    emoji: '⚡',
    category: 'Defending',
    difficulty: 3,
    duration: '10 mins',
    positions: ['Defender', 'Midfielder', 'All-Rounder'],
    equipment: ['1 ball', '2 cones', '2 players'],
    tagline: 'Know WHEN to tackle — the defender\'s most important decision.',
    description: 'Attacker dribbles at speed toward two cones placed as a goal (2m wide). Defender must decide: jockey and force wide, or commit to a tackle. Defender scores if they win the ball, attacker scores if they go through the cones.',
    steps: [
      'Set up two cones 2 metres apart as a goal',
      'Attacker starts 8 metres from the goal',
      'Defender starts between attacker and goal',
      'Attacker dribbles at speed toward the goal',
      'Defender: JOCKEY until the right moment, then tackle',
      '5 attempts each — swap roles',
    ],
    coaching_tip: 'Tackle when the ball is slightly away from their foot — that\'s your window. Never tackle when the ball is under their control.',
    xp: 25,
  },

  // ── GOALKEEPER ───────────────────────────────
  {
    id: 'gk1',
    title: 'Footwork Ladder',
    emoji: '🧤',
    category: 'Goalkeeper',
    difficulty: 1,
    duration: '8 mins',
    positions: ['Goalkeeper'],
    equipment: ['An agility ladder or cones'],
    tagline: 'Goalkeeper footwork is the foundation of everything.',
    description: 'Use an agility ladder or 8 cones spaced 50cm apart. Perform quick feet patterns — two feet in each box, side shuffle, in-out. Then explode to either side when the coach points.',
    steps: [
      'Set up the ladder or 8 cones 50cm apart',
      'High knees: two feet in each box, arms pumping',
      'Lateral shuffle: step in with right then left, step out with left then right',
      'In-out: both feet in, then straddle outside, keep moving forward',
      'After each run, freeze in ready position',
      'Coach points left or right — explode to dive that way',
    ],
    coaching_tip: 'Stay on your toes throughout — heels touching the ground slows your movement. Quick, light, precise.',
    xp: 15,
  },

  {
    id: 'gk2',
    title: 'Shot Stopping Basics',
    emoji: '🥅',
    category: 'Goalkeeper',
    difficulty: 2,
    duration: '12 mins',
    positions: ['Goalkeeper'],
    equipment: ['6 balls', 'a goal', 'a shooter'],
    tagline: 'The most fundamental skill for any goalkeeper.',
    description: 'Shooter stands 12 metres from goal. Takes 6 shots — 2 low to each corner, 2 high to each corner. Goalkeeper works on technique: footwork to set, then dive or step to save.',
    steps: [
      'Goalkeeper starts in ready position — on toes, hands up',
      'Shooter takes aim from 12 metres',
      'Low shot left corner: step across, get behind the ball, cushion save',
      'Low shot right corner: same, opposite side',
      'High shot: step across, jump, catch or parry over the bar',
      'Vary the order so the keeper doesn\'t know where it\'s going',
    ],
    coaching_tip: 'Move your feet FIRST — get your body behind the ball, then your hands. Keepers who dive without moving their feet make harder saves look easy.',
    xp: 20,
  },

  {
    id: 'gk3',
    title: 'Cross Claiming',
    emoji: '✋',
    category: 'Goalkeeper',
    difficulty: 3,
    duration: '12 mins',
    positions: ['Goalkeeper'],
    equipment: ['6 balls', 'a goal', 'crosser', '1-2 challengers'],
    tagline: 'Own your box — don\'t let attackers dominate it.',
    description: 'Crosser delivers 6 balls from wide positions. Goalkeeper must decide: come and claim, or organise defenders to head it away. When coming, call "KEEPER!" loudly and take the ball at its highest point.',
    steps: [
      'Crosser stands 15 metres wide with 6 balls',
      'One or two players in the box as challengers',
      'Crosser delivers when keeper signals ready',
      'Keeper: decide instantly — come or stay',
      'If coming: call "KEEPER!" loudly, jump off one foot, catch at highest point',
      'If staying: shout "AWAY!" and direct the defender',
    ],
    coaching_tip: 'Commit fully — half-hearted claims lead to collisions and dropped balls. If you\'re coming, COME. If you\'re staying, STAY.',
    xp: 25,
  },

  // ── FITNESS & AGILITY ─────────────────────────
  {
    id: 'fi1',
    title: 'Sprint and Touch',
    emoji: '⚡',
    category: 'Fitness',
    difficulty: 2,
    duration: '8 mins',
    positions: ['All'],
    equipment: ['4 cones'],
    tagline: 'Football-specific speed — short, sharp, explosive.',
    description: 'Set up 4 cones in a 10x10 metre square. Sprint to each cone in order, touch it with your hand, then sprint back to the start. Rest 30 seconds between each set. Do 6 sets.',
    steps: [
      'Set up 4 cones at corners of a 10x10 metre square',
      'Start at cone 1',
      'Sprint to cone 2, touch it with your hand',
      'Sprint back to cone 1',
      'Sprint to cone 3 (diagonal), touch, sprint back',
      'Sprint to cone 4, touch, sprint back — that\'s one set. Rest 30 seconds. Repeat 6 times.',
    ],
    coaching_tip: 'Drive your arms — arm speed creates leg speed. Sprint low on the way, stay low through the turn.',
    xp: 15,
  },

  {
    id: 'fi2',
    title: 'Box to Box Runs',
    emoji: '🏃',
    category: 'Fitness',
    difficulty: 3,
    duration: '12 mins',
    positions: ['Midfielder', 'All-Rounder'],
    equipment: ['4 cones'],
    tagline: 'Build the engine that runs the game.',
    description: 'Simulate a box-to-box midfielder\'s run. Sprint from one penalty area to the other (approx. 68 metres). Walk back. Repeat 8 times. Time your sprints and try to keep within 2 seconds of your best time.',
    steps: [
      'Mark the two penalty areas with cones if outside',
      'Start at one penalty area',
      'Sprint flat out to the other penalty area',
      'Time it — note your time',
      'Walk back (this is your rest)',
      'Repeat 8 times — try to stay within 2 seconds of your first sprint time',
    ],
    coaching_tip: 'The test isn\'t how fast you go — it\'s how consistent you are. If your times drop massively, you\'re going too fast early.',
    xp: 20,
  },

  {
    id: 'fi3',
    title: 'Reaction Ball Drill',
    emoji: '👁️',
    category: 'Fitness',
    difficulty: 2,
    duration: '8 mins',
    positions: ['All'],
    equipment: ['1 ball', '2 cones'],
    tagline: 'Train your reactions — football is about split-second decisions.',
    description: 'Two players stand 5 metres apart. One holds the ball and without warning drops it. The other must react immediately and sprint to reach the ball before it bounces twice. Swap after 10 reactions.',
    steps: [
      'Two players stand 5 metres apart',
      'Player A holds the ball at chest height',
      'Player B stands ready in athletic position',
      'Without warning, Player A drops the ball',
      'Player B must reach the ball before it bounces twice',
      '10 reactions each — count successes',
    ],
    coaching_tip: 'Stay in athletic position — weight forward, on toes, knees bent. A reaction from a flat-footed position is half a second slower.',
    xp: 15,
  },

  // ── TACTICS ──────────────────────────────────
  {
    id: 'ta1',
    title: 'Shadow Play (Without Ball)',
    emoji: '📐',
    category: 'Tactics',
    difficulty: 2,
    duration: '10 mins',
    positions: ['All'],
    equipment: ['Cones to mark zones', 'A coach or leader'],
    tagline: 'Learn your shape before the ball is involved.',
    description: 'The team walks through their formation and movement patterns without a ball. Coach calls out scenarios ("ball wide right", "press trigger", "counter") and players move to their correct positions.',
    steps: [
      'Mark out a half-pitch with cones showing zones',
      'Players take their starting positions in formation',
      'Coach calls "ball at right back" — everyone shifts shape accordingly',
      'Coach calls "press trigger" — everyone moves to press positions',
      'Coach calls "ball lost centrally" — everyone drops into defensive shape',
      'Walk through it 3 times, then jog through it 3 times',
    ],
    coaching_tip: 'Shadow play looks boring but it\'s how the best teams in the world install their patterns. When the ball comes, the shape is automatic.',
    xp: 20,
  },

  {
    id: 'ta2',
    title: 'Possession Square',
    emoji: '🔷',
    category: 'Tactics',
    difficulty: 2,
    duration: '15 mins',
    positions: ['All'],
    equipment: ['1 ball', 'cones for a 15x15m square', '6+ players'],
    tagline: 'Keeping the ball under tactical pressure.',
    description: 'Mark a 15x15 metre square. 4 players keep possession against 2 defenders inside the square. Possession team scores a point for every 5 consecutive passes. Defenders swap when they win it.',
    steps: [
      'Mark a 15x15 metre square with cones',
      '4 players spread around the outside/inside, 2 defenders inside',
      'Possession team tries to keep the ball',
      'Score 1 point for every 5 consecutive passes without losing the ball',
      'When defenders win it, the player who lost it becomes a defender',
      'Play for 10 minutes — track the score',
    ],
    coaching_tip: 'The player WITHOUT the ball is the most important — you must constantly move to offer an angle. Don\'t stand and watch.',
    xp: 20,
  },

  {
    id: 'ta3',
    title: 'Pressing Pattern Drill',
    emoji: '⚡',
    category: 'Tactics',
    difficulty: 3,
    duration: '12 mins',
    positions: ['All'],
    equipment: ['1 ball', 'cones', '6+ players', 'bibs'],
    tagline: 'Press as a unit — not as individuals.',
    description: 'Set up a 30x20 metre zone. Blue team plays out from the back. Red team must press in a coordinated shape — when the trigger occurs (back pass to GK), all three forwards press simultaneously.',
    steps: [
      'Mark a 30x20 zone — one team defends, one presses',
      'Defending team starts with the ball at the back',
      'Pressing team waits for the trigger (coach signals or back pass occurs)',
      'On trigger: all three forwards press simultaneously in their correct angles',
      'Goal: force the long ball or win possession within 6 seconds',
      'Reset if not won in 6 seconds — analyse what went wrong',
    ],
    coaching_tip: 'Press at an ANGLE — not straight at the player. An angled press cuts off the back pass and forces the ball in one direction.',
    xp: 25,
  },

  // ── MENTAL / AWARENESS ────────────────────────
  {
    id: 'aw1',
    title: 'Head Up Dribbling',
    emoji: '👁️',
    category: 'Awareness',
    difficulty: 2,
    duration: '10 mins',
    positions: ['All'],
    equipment: ['1 ball', '4 cones', 'a partner'],
    tagline: 'Dribble AND see what\'s around you.',
    description: 'Dribble around a 10x10 metre square. Partner stands outside the square and holds up a number of fingers (1-5). You must call out the number while dribbling — without looking down at the ball.',
    steps: [
      'Mark a 10x10 metre square with cones',
      'Start dribbling around the outside of the square',
      'Partner stands outside with hand raised showing fingers',
      'Call out the number of fingers WITHOUT looking down',
      'Partner changes the number randomly every 5-10 seconds',
      '3 minutes clockwise, 3 minutes anticlockwise',
    ],
    coaching_tip: 'Use your peripheral vision — you should be able to feel the ball at your feet and see your partner at the same time.',
    xp: 15,
  },

  {
    id: 'aw2',
    title: 'Scanning Before Receiving',
    emoji: '🔍',
    category: 'Awareness',
    difficulty: 3,
    duration: '10 mins',
    positions: ['Midfielder', 'All-Rounder'],
    equipment: ['1 ball', '4 cones', '3+ players'],
    tagline: 'The elite habit that separates good players from great ones.',
    description: 'Before every pass is played to you, you must look over both shoulders. A coach or partner monitors this — you lose a point every time you receive without scanning first.',
    steps: [
      'Set up a passing triangle or square with 3-4 players',
      'A "monitor" watches — they can be a coach or spare player',
      'Before every pass is played TO you, you must turn and scan both shoulders',
      'The monitor calls "SCAN!" if you don\'t look before receiving',
      'Score: minus 1 point for every missed scan',
      'Play for 5 minutes — aim for zero minus points',
    ],
    coaching_tip: 'Scan BEFORE the ball is played — once it\'s coming it\'s too late. The best midfielders scan every 2-3 seconds constantly.',
    xp: 25,
  },

  // ── POSITION SPECIFIC ─────────────────────────
  {
    id: 'st1',
    title: 'Striker\'s Diagonal Run',
    emoji: '⚡',
    category: 'Movement',
    difficulty: 2,
    duration: '10 mins',
    positions: ['Striker', 'All-Rounder'],
    equipment: ['4 balls', 'cones', 'a goal', '2 players'],
    tagline: 'The run that stretches every defence.',
    description: 'Start central, make a diagonal run toward the corner of the penalty area. Midfielder plays the ball into the channel. Striker must receive on the run and finish. Alternate diagonal runs left and right.',
    steps: [
      'Striker starts at the penalty spot, facing the midfielder',
      'Midfielder stands 20 metres away with the ball',
      'Striker drops deep, then suddenly makes a diagonal run left',
      'Midfielder plays the ball into the channel ahead of the run',
      'Striker receives, takes 1 touch, and finishes',
      'Repeat to the right. 5 runs each side.',
    ],
    coaching_tip: 'The fake drop before the run is what creates the separation — commit to the drop, then explode diagonally.',
    xp: 20,
  },

  {
    id: 'mi1',
    title: 'Midfielder\'s Receive and Drive',
    emoji: '🎯',
    category: 'Movement',
    difficulty: 2,
    duration: '10 mins',
    positions: ['Midfielder', 'All-Rounder'],
    equipment: ['4 balls', 'cones', '2 players'],
    tagline: 'Receive deep, drive forward — the midfielder\'s heartbeat.',
    description: 'Receive a back pass from a defender position, then drive forward 10 metres with the ball before playing a forward pass. Simulates the midfielder receiving and breaking lines.',
    steps: [
      'Defender stands 10 metres behind with ball',
      'Midfielder faces away and calls for the ball',
      'Receives and turns in one movement',
      'Drives forward 10 metres with the ball under close control',
      'Plays a forward pass to a target player or into a zone',
      'Jog back and repeat — 8 repetitions',
    ],
    coaching_tip: 'The first touch should set you up to drive forward — not sideways, not back. One touch, forward, drive.',
    xp: 20,
  },

  {
    id: 'de5',
    title: 'Defender\'s Step and Cover',
    emoji: '🛡️',
    category: 'Defending',
    difficulty: 3,
    duration: '10 mins',
    positions: ['Defender', 'All-Rounder'],
    equipment: ['1 ball', 'cones', '3 players'],
    tagline: 'The CB partnership in action — step and cover.',
    description: 'Two centre-backs work together. CB1 steps aggressively to press the ball. CB2 drops and covers the space behind. Practice the communication and movement until it\'s instinctive.',
    steps: [
      'Set up two centre-backs side by side',
      'Attacker starts 15 metres ahead with the ball',
      'CB1 steps forward aggressively to press',
      'CB2 immediately drops and shifts to cover the space CB1 has left',
      'Attacker tries to play a through ball — CB2 must be there',
      'Swap CB1 and CB2 roles after 5 repetitions',
    ],
    coaching_tip: 'CB2 must communicate immediately when CB1 steps — "I\'ve got the cover, GO!" — the verbal trigger is the key.',
    xp: 25,
  },

];

// ─────────────────────────────────────────────
//  GET TODAY'S DRILL
//  Seeded by date — same drill for everyone on
//  the same day, changes at midnight.
// ─────────────────────────────────────────────
function getTodaysDrill() {
  const seed = new Date().toDateString();
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    hash = (hash * 31 + seed.charCodeAt(i)) | 0;
  }
  const idx = Math.abs(hash) % ALL_DRILLS.length;
  return ALL_DRILLS[idx];
}

// Get drills filtered by position
function getDrillsForPosition(position) {
  if (!position || position === 'All-Rounder') return ALL_DRILLS;
  return ALL_DRILLS.filter(d =>
    d.positions.includes('All') || d.positions.includes(position)
  );
}

// Get drills by category
function getDrillsByCategory(category) {
  return ALL_DRILLS.filter(d => d.category === category);
}

const DRILL_CATEGORIES = [...new Set(ALL_DRILLS.map(d => d.category))];
